spring.application.name=emandi-backend
# ===============================
# Server Configuration
# ===============================
server.port=8080

# ===============================
# Database Configuration (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhos:t5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Emandi123
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
jwt.secret=3c20eb6949d871f4ea8f7227d9c789091a75cd4415fb92ea9c38b4523c662298
jwt.expiration=3600000



spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Logging
# ===============================
logging.level.org.springframework=INFO
logging.level.com.emandi.backend=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=26aayush2006@gmail.com
spring.mail.password=jaek yuju huzm ffza   # Not your Gmail password, use App Password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
